// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuIJe4ZyNbwvNQIgMfONKFJhx7HRIDFhM',
    appId: '1:297321674230:web:2bcef5b69f285fde9203d7',
    messagingSenderId: '297321674230',
    projectId: 'checkpointdb-a8cd7',
    authDomain: 'checkpointdb-a8cd7.firebaseapp.com',
    storageBucket: 'checkpointdb-a8cd7.firebasestorage.app',
    measurementId: 'G-P4MW4VN9ZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh7qSfclgxvTmeUJiPlg215Enp3FPrPhA',
    appId: '1:297321674230:android:6be1481adb7635f29203d7',
    messagingSenderId: '297321674230',
    projectId: 'checkpointdb-a8cd7',
    storageBucket: 'checkpointdb-a8cd7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXAVIdCCS8plEGn338MEkRUXx_CKpuptY',
    appId: '1:297321674230:ios:a7616e8ef88e702f9203d7',
    messagingSenderId: '297321674230',
    projectId: 'checkpointdb-a8cd7',
    storageBucket: 'checkpointdb-a8cd7.firebasestorage.app',
    iosBundleId: 'com.example.checkpointapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXAVIdCCS8plEGn338MEkRUXx_CKpuptY',
    appId: '1:297321674230:ios:a7616e8ef88e702f9203d7',
    messagingSenderId: '297321674230',
    projectId: 'checkpointdb-a8cd7',
    storageBucket: 'checkpointdb-a8cd7.firebasestorage.app',
    iosBundleId: 'com.example.checkpointapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuIJe4ZyNbwvNQIgMfONKFJhx7HRIDFhM',
    appId: '1:297321674230:web:7e1ef221b45ad4749203d7',
    messagingSenderId: '297321674230',
    projectId: 'checkpointdb-a8cd7',
    authDomain: 'checkpointdb-a8cd7.firebaseapp.com',
    storageBucket: 'checkpointdb-a8cd7.firebasestorage.app',
    measurementId: 'G-BRZPGNZ7N1',
  );

}